import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Structured sidebar with custom category headings
  tutorialSidebar: [
    // USING PODGRAM.AI Section
    {
      type: 'html',
      value: 'USING PODGRAM.AI',
      className: 'sidebar-category-heading',
    },
    'welcome',
    'quick-start-guide',
    'faq',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started',
        },
      ],
    },
    {
      type: 'category',
      label: 'Prompting Guide',
      link: {
        type: 'generated-index',
        description: 'Master the art of AI image generation with PODgram.ai. Learn essential prompting techniques, best practices, and advanced strategies to create stunning artwork for your print-on-demand business.'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'prompting-guide',
        },
      ],
    },
    {
      type: 'category',
      label: 'Features',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'features',
        },
      ],
    },

    // PLANS AND PRICING Section
    {
      type: 'html',
      value: 'PLANS AND PRICING',
      className: 'sidebar-category-heading',
    },
    'plans',

    // LEGAL & SUPPORT Section
    {
      type: 'html',
      value: 'LEGAL & SUPPORT',
      className: 'sidebar-category-heading',
    },
    'support',
    'privacy-policy',
    'terms-of-service',

    // ABOUT PODGRAM.AI Section
    {
      type: 'html',
      value: 'ABOUT PODGRAM.AI',
      className: 'sidebar-category-heading',
    },
    'company',
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
